name: Compile

on:
  push:
    branches: 
       - '*'
  pull_request:
    branches: 
       - master
       - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run unit tests
      run: ./gradlew common-jvm:test
    - name: Setup Android build environment
      uses: android-actions/setup-android@v2.0.2
    - name: Build Android
      run: ./gradlew android:buildErgomainnetDebug --stacktrace
    - name: Build classes iOS module
      run: ./gradlew ios:buildNeeded --stacktrace
    - name: Build desktop
      run: ./gradlew desktop:jar
