name: Create Icons

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!master'   # excludes master
    paths:
      - '**/icon.svg'

jobs:
  build:
    name: Create Icons
    runs-on: ubuntu-latest
    steps:

      # CHECKOUT CODE
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v2

      # CREATE ICONS
      - id: create-icons
        name: Create icons for different platforms
        run: |
          # Create icons for different platforms
          convert -version
          convert -background transparent -density 100 \
          -resize 64x64 \
          desktop/deploy/icon.svg \
          desktop/deploy/icon.png
          convert -background transparent -density 100 \
          -define icon:auto-resize -colors 256 \
          desktop/deploy/icon.svg \
          desktop/deploy/icon.ico

      - id: push-icons
        name: Commit icons to repository
        run: |
          # Commit icons to repository
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./desktop/deploy/icon.*
          git commit -m "Create icons for different platforms"
          git push
